name = "cf-pages-worker-d1-app"
main = "worker/index.js"
compatibility_date = "2025-09-11"

[[d1_databases]]
binding = "DB"
database_name = "tcgcollection-db"
database_id = "930fc288-9c20-4f35-b96f-6f5d485713f3"

# Do NOT put JWT_SECRET here! Use wrangler secret:
# wrangler secret put JWT_SECRET
